updatechecker:
  # enable or disable the update checker
  enabled: true
  # check for updates automatically
  auto-check: true
  # download updates automatically
  auto-download: false
  # restart the server automatically after downloading an update (only works if the command is executed by the console, auto-download will not restart the server)
  auto-restart: false

